### ISSUE TITLE
Suggestion - Edit Steam URL Protocol

### ISSUE THREAD

**Issue by JustOptimize** [Aetopia/NoSteamWebHelper#15]
Editing the `HKEY_CLASSES_ROOT\steam\Shell\Open\Command\(Default)` regedit to launch steam with NoSteamWebHelper when running a game shortcut

**Comment by Aetopia** [comment]
Steam auto fixes the registry value when it starts up.

So it doesn't help in anyway.
Instead have NoSteamWebHelper execute the specified Steam URL of choice.

**Comment by JustOptimize** [comment]
> Steam auto fixes the registry value when it starts up.

Oh right, forgot about that

> Instead have NoSteamWebHelper execute the specified Steam URL of choice.

Good Idea! Maybe add that automatically?
