### ISSUE TITLE
Virus detected by Windows Defender

### ISSUE THREAD

**Issue by Shnxxx** [Aetopia/NoSteamWebHelper#17]
I just ran it like what the instructions said. The first 1 week it was working great. But suddenly it gotten detected by Windows. I don't know why too.

![image](https://github.com/Aetopia/NoSteamWebHelper/assets/48496678/cd27b01c-dbb5-43e0-ad44-3fe88cb87fc5)

I know I can just add to exception, but I don't have control on my Windows Defender. It is being managed by my organization. Though that's the only thing they manage. Anything else can be managed since I'm an Admin.

**Comment by Aetopia** [comment]
Windows Defender will attack anything that isn't code signed.
Your best option would be to submit here: https://www.microsoft.com/en-us/wdsi/filesubmission
and flag the file as safe.

Aside from that whatever is happening is out of my hand.
