### ISSUE TITLE
How to uninstall of disable?

### ISSUE THREAD

**Issue by EthanTPlayer05** [Aetopia/NoSteamWebHelper#20]
The Reason i want to uninstall of disable because i deeply always thinking this is a virus, and want the steamwebhelper back after i upgraded my pc

**Comment by Aetopia** [comment]
Just delete any files related to NoSteamWebHelper?

**Comment by EthanTPlayer05** [comment]
i delete the 2 files but does it have a folder? i couldnt find it?

**Comment by Aetopia** [comment]
No, it doesn't.
