### ISSUE TITLE
Latest updates from steam made it laggy while navigating.

### ISSUE THREAD

**Issue by BehaDev** [Aetopia/NoSteamWebHelper#21]
Title.

**Comment by Aetopia** [comment]
NoSteamWebHelper disables GPU Accelerated WebViews so the WebHelper processes can disabled properly.

**Comment by Aetopia** [comment]
Please try: https://github.com/Aetopia/NoSteamWebHelper/releases/tag/v4.1.3

**Comment by vintotal** [comment]
Is this update necessary if running an older version of the steam client?

**Comment by BehaDev** [comment]
> Is this update necessary if running an older version of the steam client?

steam updates itself no matter what mate.

**Comment by BehaDev** [comment]
> Please try: https://github.com/Aetopia/NoSteamWebHelper/releases/tag/v4.1.3

Fixed with this newest release , thank you and imma close this issue.
