### ISSUE TITLE
[QUESTION] What are the best Steam launch options to use along with -silent?

### ISSUE THREAD

**Issue by EternalTranquility1** [Aetopia/NoSteamWebHelper#23]
Do you recommend adding any other options, or is -silent enough on its own?

**Comment by Aetopia** [comment]
I recommend adding in `-silent` so NoSteamWebHelper doesn't forcefully restart Steam leading to longer launch times.

**Comment by Aetopia** [comment]
> I get it, so -silent alone is enough.

Just note, `-silent` is only required so the CEF doesn't pop-up when its restored.
