### ISSUE TITLE
also QUESTION: Should i be worried about getting VAC banned for using Steam with the new DLL?

### ISSUE THREAD

**Issue by EternalTranquility1** [Aetopia/NoSteamWebHelper#24]
Is it safe? 😨

**Comment by Aetopia** [comment]
Quotes from Steam's support post on [VAC](https://help.steampowered.com/en/faqs/view/571A-97DA-70E9-FF74):

> The VAC system reliably detects cheats using their cheat signatures. Any third-party modifications to a game designed to give one player an advantage over another is classified as a cheat or hack and will trigger a VAC ban. This includes modifications to a game's core executable files and dynamic link libraries.

> Use caution when installing any game modifications like scripts or custom skins, and only download custom content from trusted sources. Hackers may maliciously disguise their cheats to cause others to get banned.
For more information on how you can protect yourself and your account, please refer to our [Account Security Recommendations](https://help.steampowered.com/en/faqs/view/6639-EB3C-EC79-FF60) help article.

NoSteamWebHelper isn't a game client modification, it's a Steam Client modification.
Additionally the latest release doesn't differ in anyway to the previous release.
I have just removed the requirement for having an injector.

As for Steam automatically loading in NoSteamWebHelper that's a quirk with how Windows finds & load dynamic link libraries into processes. Leveraging that allows NoSteamWebHelper to go entirely injectorless.
