### ISSUE TITLE
Steam doesn't reopen after exiting a game //

### ISSUE THREAD

**Issue by BehaDev** [Aetopia/NoSteamWebHelper#25]
After newest release , after exiting the game , steam doesn't reopen , which is a struggle for me since i play without explorer.exe , so i have to re-run explorer.exe to reopen steam via system tray , appreciated the newest release btw , thanks to it i can use my controller without DS4 since steamwebhelper.exe didn't support my PS4 unless i use DS4 or normal steam , which was a struggle , thanks again.

**Comment by BehaDev** [comment]
Update : The controller  works on some games and not on other games ( same problem with older versions ) ,also in EA related games , steam stuck on synchornizing so it wont open and i have to kill process and relaunch it overagain.

**Comment by Aetopia** [comment]
NoSteamWebHelper will automatically have Steam start silently so the CEF UI doesn't popup when it is restored.

I think it would be better to just allow the user to decide on this behavior.

**Comment by Aetopia** [comment]
Please try the latest release.

**Comment by BehaDev** [comment]
> Please try the latest release.

Same issue , im not applying the -silent arg btw..

**Comment by BehaDev** [comment]
it applied the first time i copied new release and didn't reopen after exiting the game again after.

**Comment by Aetopia** [comment]
Which game exactly?

**Comment by BehaDev** [comment]
> Which game exactly?

Tried at the moment Overwatch and the finals.

**Comment by Aetopia** [comment]
The code for detecting running apps isn't perfect by any means. That's why a tray icon is provided to toggle the CEF.

**Comment by BehaDev** [comment]
> The code for detecting running apps isn't perfect by any means. That's why a tray icon is provided to toggle the CEF. If you want to potentially older features/behaviors consider using an older version of NoSteamWebHelper. But I will give users the ability to configure the CEF window behavior via Steam's command line arguments.

personally im going to keep using this version , since last versions breaks so game that won't launch ( EA games related ) also my controller won't work in some unless i run the default steam version ) , but about this release , the steam and nosteamwebhelper works sucessfully ( unless it an EA game the steam gets stuck in synchronizing and i have to relaunch it overagain ) , the only problem is , as i said , steam doesn't reopen after exiting the games , and i have to go through the tray but im still thankful for the releases.
