### ISSUE TITLE
No SteamWeb Helper not working?

### ISSUE THREAD

**Issue by BGT00** [Aetopia/NoSteamWebHelper#26]
![stea](https://github.com/user-attachments/assets/f60db8d0-a568-4650-8321-3a44d0c72fd8)

Am I doing something wrong or what? Your add-on doesn't really work for me.
After placing the file in the steam folder I still have web processes.
Can I ask for help?

**Comment by Aetopia** [comment]
Intentional due to the fact, Steam fully relies on the CEF to even launch games.

Because of that NoSteamWebHelper toggles the CEF off when an app is running.

**Comment by BGT00** [comment]
when I run CS2, do these processes have to run anyway?

**Comment by Aetopia** [comment]
The code for detecting running apps isn't perfect, you can always toggle the CEF manually.

**Comment by BGT00** [comment]
> The code for detecting running apps isn't perfect, you can always toggle the CEF manually.

how could i change it manually? I fight with these processes because they take up a lot of RAM and CPU

**Comment by Aetopia** [comment]
Use the provided tray icon.

**Comment by BGT00** [comment]
> Use the provided tray icon.

I must be too stupid because I don't know where she is

**Comment by Aetopia** [comment]
Notification Area of the taskbar.
![image](https://github.com/user-attachments/assets/6ec341b4-9279-4eae-bc84-46e2f7ab49a4)
