### ISSUE TITLE
Steam closes itself after some time (v2.0)

### ISSUE THREAD

**Issue by 3nly** [Aetopia/NoSteamWebHelper#3]
First of all, thank you for making this.

I've run into this issue of Steam closing itself after an *undetermined* amount of time on two occasions now:
- Just having Steam open and not doing anything
- Running a game

Didn't seem to be happening with version 1.1. I think at some point something happens and Steam just crashes silently.
Using Windows 10 LTSC 21H2.

**Comment by Aetopia** [comment]
That's actually something I intentionally added:
```c
void WinEventProc(
    HWINEVENTHOOK hWinEventHook,
    DWORD event,
    HWND hWnd,
    LONG idObject,
    LONG idChild,
    DWORD idEventThread,
    DWORD dwmsEventTime)
{
    if ((event != EVENT_OBJECT_HIDE ||
         event != EVENT_OBJECT_SHOW) &&
        idObject != OBJID_WINDOW &&
        idChild != CHILDID_SELF)
        return;
    UnhookWinEvent(hWinEventHook);
    if (event == EVENT_OBJECT_SHOW)
        TerminateProcess(GetCurrentProcess(), 0);
    SteamWndProc = (WNDPROC)GetWindowLongPtrW(hWnd, GWL_WNDPROC);
    SetWindowLongPtrW(hWnd, GWL_WNDPROC, (LONG_PTR)NoBrowserWndProc);
    PostQuitMessage(0);
}
```

If Steam shows its window when starting up then the WebHelper will not be disabled properly by NoSteamWebHelper, i.e this can causes Steam to use more CPU cycles then required.

Have you tried to start the Steam Client normally?

**Comment by 3nly** [comment]
I think I get what you're saying, but isn't closing the Steam client while your game is running unwanted behavior?

>Have you tried to start the Steam Client normally?
I have and do when I want to check the store.
