### ISSUE TITLE
Performance Issues when NoSteamWebHelper suspends the WebHelper process.

### ISSUE THREAD

**Issue by Aetopia** [Aetopia/NoSteamWebHelper#4]
It seems for specific games, NoSteamWebHelper is causing performance issues when the webhelper is suspended.<br>
Likely reason is that these games seem to be dependent on some webhelper component (likely the game overlay).<br>
I haven't seen any performance issues (likely due to me playing Halo Infinite and Halo MCC via Steam) but these performance issues should be tested with a variety of games.

**Comment by Exoulos** [comment]
Noticed in Kovaaks FPS Aim Trainer https://github.com/Aetopia/NoSteamWebHelper/issues/4 that FPS drops would be constant when using NoSteamWebHelper
