### ISSUE TITLE
No longer finds steam

### ISSUE THREAD

**Issue by vintotal** [Aetopia/NoSteamWebHelper#5]
1. Killed steam process
2. Extracted zip in steam main folder
3. Double-click NoSteamWebHelper.exe
4. See this message of not finding steam.exe

![imagen](https://github.com/Aetopia/NoSteamWebHelper/assets/1743914/36de9452-1e11-4d44-b1b0-ee4438f543c5)

My steam version:
![imagen](https://github.com/Aetopia/NoSteamWebHelper/assets/1743914/946f378f-2d95-4eae-ab8a-338daba15729)

Version 2.1 worked. Merci 😉

**Comment by Aetopia** [comment]
Thank you for reporting, I will quickly push out a patch that addresses this issue.

**Comment by Aetopia** [comment]
https://github.com/Aetopia/NoSteamWebHelper/releases/tag/v3.0.1

Please try v3.0.1 and see if that fixes the issue.

**Comment by vintotal** [comment]
I think it worked. The results show similar RAM usage though.

Memory usage with this commandline:
NoSteamWebHelper.exe  -noverifyfiles -nobootstrapupdate

![imagen](https://github.com/Aetopia/NoSteamWebHelper/assets/1743914/4f94581b-8037-481c-867a-1a3426ac78cd)

Memory usage with this commandline:
steam.exe -noverifyfiles -nobootstrapupdate
![imagen](https://github.com/Aetopia/NoSteamWebHelper/assets/1743914/88760674-88ca-4a4b-a29a-a20dc4423751)

**Comment by Aetopia** [comment]
> I think it worked. The results of different commandlines show similar RAM usage though with version 3.0.1. The memory usage with 2.1 was very lower.
> 
> Memory usage with this commandline: NoSteamWebHelper.exe -noverifyfiles -nobootstrapupdate
> 
> **Version 3.0.1** ![imagen](https://user-images.githubusercontent.com/1743914/263240061-4f94581b-8037-481c-867a-1a3426ac78cd.png)
> 
> **Version 2.1** ![imagen](https://user-images.githubusercontent.com/1743914/263243625-24f10046-5c23-4536-8285-be3f7bf078bb.png)
> 
> Memory usage with this commandline: steam.exe -noverifyfiles -nobootstrapupdate
> 
> ![imagen](https://user-images.githubusercontent.com/1743914/263238096-88760674-88ca-4a4b-a29a-a20dc4423751.png)
> 
> Memory usage with this commandline: NoSteamWebHelper.exe -vgui -oldtraymenu -noverifyfiles -nobootstrapupdate -skipinitialbootstrap -single_core -norepairfiles -overridepackageurl -no-browser -cef-single-process -cef-disable-breakpad
> 
> **Version 3.0.1** ![imagen](https://user-images.githubusercontent.com/1743914/263240648-fc6b5fee-2375-4d27-9962-d8d43524100c.png)
> 
> **Version 2.1** ![imagen](https://user-images.githubusercontent.com/1743914/263242133-3398e5d5-ba3c-440b-b0b4-e48c41f2a7c0.png)

I can no longer get the VGUI aka the non WebHelper to launch at all.

Thus the webhelper is disabled when an app runs.

**Comment by Aetopia** [comment]
I will close this issue now.
