### ISSUE TITLE
same issue as issue #5

### ISSUE THREAD

**Issue by maciek1414** [Aetopia/NoSteamWebHelper#6]
![image](https://github.com/Aetopia/NoSteamWebHelper/assets/144180215/81fef737-983c-4b62-a99a-2093f484b07d)

"Windows cannot find steam.exe"

**Comment by Aetopia** [comment]
Did you try using the latest version?

**Comment by maciek1414** [comment]
> Did you try using the latest version?

yes

**Comment by maciek1414** [comment]
ISSUE FIXED
i used 3.0 version, one version backwards, it works now :)

**Comment by maciek1414** [comment]
actually nvm, it does find steam but doesnt kill the process :(
![image](https://github.com/Aetopia/NoSteamWebHelper/assets/144180215/2fb939ca-7735-4fcc-a163-e14d3eb9f7da)

**Comment by Aetopia** [comment]
The webhelper is killed at game runtime, launch a game and the webhelper will be killed.
