### ISSUE TITLE
Steam spawns "Sign into Steam" process

### ISSUE THREAD

**Issue by simonemike95** [Aetopia/NoSteamWebHelper#9]
Unsure if this is still being developed/maintained, but when I ran this it did indeed stop all the web helper processes, but Steam took it upon itself to spawn a "Sign Into Steam" process, which seems to be the amalgamation of all the web helper processes (or at least the memory usage of them). It only shows up when I run NoSteamWebHelper.exe and takes up ~500MB of RAM.

**Comment by Aetopia** [comment]
The program forces the CEF to confine itself to a single process. The RAM usage is practically the same as single/multi process.

**Comment by simonemike95** [comment]
Ahh, I misunderstood the goal of this then. Thought it mitigated the crazy RAM usage from Steam, thanks!
